#------------------------------------------
# GitHub Action Workflow
#
# Version      Date        Info
# 1.0                  
#
# Made by Andrei Bakaushyn  
#-------------------------------------------

name: Gets_all_changed_files_find_tabs.

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name   : find-tabs

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: find
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: tab
        run: |
         for changed_file in ${{ steps.files.outputs.all }}; do
         echo "File ${changed_file} checked, tab found" >> TAB.log
         grep -P '\t' ${changed_file} | sort -n >> TAB.log
         done
         
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: TAB.log 
