name: KinD Cluster Setup

on:
  push:
    branches:
      - main

jobs:
  setup-kind:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1" # Убедитесь, что вы используете последнюю доступную версию
          config: |
            kind: Cluster
            apiVersion: kind.x-k8s.io/v1alpha4
            nodes:
            - role: control-plane
              image: kindest/node:v1.29.1

      - name: Get Cluster Info
        run: |
          kubectl cluster-info --context kind-kind-test-cluster
          kubectl get nodes
